/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: security
  action: login

/forgot-password:
  controller: security
  action: resetPassword

/logout:
  controller: security
  action: logout

/register:
  controller: security
  action: register

/admin:
  controller: admin
  action: dashboard

/admin/dashboard:
  controller: admin
  action: dashboard

/admin/users:
  controller: users
  action: users

/admin/pages:
  controller: pages
  action: pages

/admin/products:
  controller: products
  action: products

/admin/comments:
  controller: comments
  action: comments

/admin/customization:
  controller: customization
  action: customization