/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: security
  action: login

/logout:
  controller: security
  action: logout

/register:
  controller: security
  action: register


/dashboard:
  controller: admin
  action: dashboard