/:
  controller: general
  action: home
  roles: []

/login:
  controller: security
  action: login
  roles: []

/logout:
  controller: security
  action: logout
  roles: []

/register:
  controller: security
  action: register
  roles: []

/dashboard:
  controller: admin
  action: dashboard
  roles: ["admin"]

/dashboard/users:
  controller: admin
  action: users
  roles: ["admin"]

/sitemap:
  controller: seo
  action: displaySitemap
  roles: []

/robots:
  controller: seo
  action: displayRobots
  roles: []