/:
  controller: general
  action: home

/sitemap:
  controller: sitemap
  action: display

/me-contacter:
  controller: general
  action: contact

/login:
  controller: security
  action: login

/logout:
  controller: security
  action: logout

/register:
  controller: security
  action: register

/admin:
  controller: admin
  action: dashboard

/admin/dashboard:
  controller: admin
  action: dashboard

/medias:
  controller: admin
  action: medias
