/:
  controller: general
  action: home

/sitemap:
  controller: sitemap
  action: display

/me-contacter:
  controller: general
  action: contact

/login:
  controller: security
  action: login

/logout:
  controller: security
  action: logout

/register:
  controller: security
  action: register

/admin:
  controller: admin
  action: dashboard

/admin/dashboard:
  controller: admin
  action: dashboard

/dashboard/medias:
  controller: admin
  action: medias

/dashboard/medias/new:
  controller: admin
  action: newMedia


/dashboard/articles:
  controller: admin
  action: articles

/dashboard/articles/new:
  controller: admin
  action: newArticle

/dashboard/users:
  controller: admin
  action: users
