/:
  controller: general
  action: home

/login:
  controller: general
  action: login

/logout:
  controller: general
  action: logout

/register:
  controller: general
  action: register

/dashboard:
  controller: admin
  action: dashboard
  roles: ["admin"]

/sitemap:
  controller: sitemap
  action: sitemap