/:
  controller: general
  action: home
  roles: []

/me-contacter:
  controller: general
  action: contact
  roles: []

# SecurityController
/login:
  controller: security
  action: login
  roles: []

/forgot-password:
  controller: security
  action: resetPassword
  roles: []

/logout:
  controller: security
  action: logout
  roles: []

/register:
  controller: security
  action: register
  roles: []

# DashboardController
/admin:
  controller: dashboard
  action: main
  roles: ["admin"]

/admin/dashboard:
  controller: dashboard
  action: main
  roles: ["admin"]

# UsersController
/admin/users:
  controller: users
  action: main
  roles: ["admin"]

/admin/user/new:
  controller: users
  action: add
  roles: ["admin"]

/admin/users/edit:
  controller: users
  action: edit
  roles: ["admin"]  


# PagesController
/admin/pages:
  controller: pages
  action: main
  roles: ["admin"]

/admin/page/new:
  controller: pages
  action: add
  roles: ["admin"]

/admin/page:
  controller: pages
  action: edit
  roles: ["admin"]  

# ProductController
/admin/products:
  controller: products
  action: main
  roles: ["admin"]

/admin/product/new:
  controller: products
  action: add
  roles: ["admin"]

/admin/product:
  controller: products
  action: edit
  roles: ["admin"]

# CommentsController
/admin/comments:
  controller: comments
  action: main
  roles: ["admin"]

# CustomizationController
/admin/customization:
  controller: customization
  action: customization

/setup:
  controller: setup
  action: setup
  roles: []
