/:
  controller: general
  action: home

/login:
  controller: security
  action: login

/logout:
  controller: security
  action: logout

/register:
  controller: security
  action: register

/dashboard:
  controller: admin
  action: dashboard
  roles: ["admin"]

/dashboard/users:
  controller: admin
  action: users
  roles: ["admin"]

/sitemap:
  controller: seo
  action: displaySitemap

/robots:
  controller: seo
  action: displayRobots